# Generated by Django 4.0.10 on 2023-03-02 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FolderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('level', models.CharField(max_length=20)),
                ('semester', models.CharField(choices=[('first', 'FIRST'), ('second', 'SECOND')], default='first', max_length=50)),
            ],
            options={
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='PDFModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.URLField()),
                ('download', models.URLField()),
                ('size', models.CharField(max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_file', to='api.foldermodel')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
